name: Publish Gem

on: [create, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@5dfdb61
        if: contains(github.ref, 'refs/tags/v')
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
